/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption } from '@/utlis'
import rootMixins from '@/routes/root-mixins'
import GlobalLayout from "@/layout/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
    {
        path: '*',
        component: GlobalLayout
    }
]
