/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "../../root-mixins/updateMeta"
import m1 from "../../root-mixins/plugin-active-header-links.js"
import m2 from "../../root-mixins/plugin-nprogress.js"
import m3 from "../../root-mixins/vuepress-plugin-smooth-scroll"

export default [
  m0,
  m1,
  m2,
  m3
]
